language: php
env: 
  - OSTICKET_VERSION=1.9.16
  - OSTICKET_VERSION=1.10.1
  
matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.6
    - php: 7.1
  fast_finish: true
  allow_failures:
    - php: 5.3
      env: OSTICKET_VERSION=1.10.1

install:
  - wget "https://github.com/osTicket/osTicket/archive/v${OSTICKET_VERSION}.tar.gz" -O ot.tgz
  - tar xvf ot.tgz && mv osTicket-${OSTICKET_VERSION} ../osticket

before_script:
  - phpenv config-rm xdebug.ini
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
