language: php
php:
  - '5.6'
  - '7.1'

matrix:
  - fast_finish: true
  
install:
  - if ! [ -f ../osticket/README.md ]; then wget https://github.com/osTicket/osTicket/archive/v1.10.1.tar.gz -O ot.tgz; fi
  - if ! [ -f ../osticket/README.md ]; then tar xvf ot.tgz && mv osTicket-1.10.1 ../osticket; fi

cache:
  directories:
  - ../osticket

before_script:
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
